name: Java CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build & Test (Maven)
        run: mvn -B clean test package

      - name: Run demo (prints to logs)
        run: java -cp target/classes com.marcelo.bank.Demo

      - name: Upload artifacts (jar + test reports)
        uses: actions/upload-artifact@v4
        with:
          name: jar-and-reports
          path: |
            target/*.jar
            target/surefire-reports/**
